### ISSUE TITLE
Accessing endpoint using SSL like wss://…

### ISSUE THREAD

**Issue by blazer82** [isapir/lucee-websocket#14]
How would you go about accessing the websocket over SSL?
We switched our page to https only, so Apache won't allow any unencrypted protocol upgrade requests.

When trying to access the endpoint using **wss://** instead of **ws://** there's an SSL handshake error -9847.

Any clues on how to do this are appreciated.

**Comment by blazer82** [comment]
I got it working behind an Apache proxy. Basically something like this:

    ProxyPassMatch ^/ws/(.*) ws://…:8888/ws/$1

**Comment by paologroppo** [comment]
Hi blazer82, I have the same handshake problem over https. Could you please tell me where to use ProxyPassMatch... to solve the problem? Thanks in advance

**Comment by blazer82** [comment]
@paologroppo I honestly can't remember the exact solution and I don't have access to that code base anymore. You basically need to configure your apache (that is if you use apache!) to forward _wss_ requests to your local _ws_. I suppose the line posted above is all you need (maybe with a modified port number?). I suggest to look up the _ProxyPassMatch_ directive of apache for more information.
