### ISSUE TITLE
JSON not valid

### ISSUE THREAD

**Issue by LanceLake** [isapir/lucee-websocket#4]
I just tried using this and I notice that it is producing the following json.

Object {MESSAGE: "Hello", TIMESTAMP: 1497640931522, CHANNEL: "default", FROM: "GM"}

When THIS is what it should be producing to be valid JSON.

Object {"MESSAGE": "Hello", "TIMESTAMP": 1497640931522, "CHANNEL": "default", "FROM": "GM"}

**Comment by isapir** [comment]
User had malformed JavaScript code
