### ISSUE TITLE
	ClassFormatError:net/twentyonesolutions/lucee/websocket/functions/WebsocketRegister : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by LanceLake** [isapir/lucee-websocket#5]
Application.cfc

http://prntscr.com/fl126b

Error when running...

http://prntscr.com/fl12fl

I am running version..

http://prntscr.com/fl137g

**Comment by LanceLake** [comment]
If it helps, I just upgraded from Lucee 4.5 to Lucee 5.1.3.18. That may be the issue.

**Comment by isapir** [comment]
Java Runtime Environment version 8 or newer is required
