### ISSUE TITLE
Can't install newest version 2.0.1

### ISSUE THREAD

**Issue by Yamaha32088** [isapir/lucee-websocket#8]
I am trying to install the latest release through the web interface but keep getting the error `/opt/lucee/tomcat/temp/servlet-filter-utils-1.1.1.jar (No such file or directory)` I have verified that I downloaded and placed that file inside the `/opt/lucee/tomcat/lib` folder like it says in the instructions. I have checked that the file was owned by the same user Lucee is running as and that the permissions were set correctly. I have tried to copy the file into the `/opt/lucee/tomcat/temp` folder as well but the same error happens and the file is immediately deleted after trying to install the extension. 

Downloading the `.lex` file and placing it inside the Lucee deploy directory yields the same results as well. 

I have double and triple checked that I did not miss a step during the install process but no success. I am running Lucee 5.1.3.18 Tomcat 8.0.43 and Java 1.8.0_121

**Comment by isapir** [comment]
Where do you see that error message?  Is there a stack trace or any other details?

**Comment by Yamaha32088** [comment]
![image](https://user-images.githubusercontent.com/6120946/28282234-6146e818-6aef-11e7-93cf-95335c5a2354.png)
It appears after selecting the extension version and clicking install under the web admin.

**Comment by Yamaha32088** [comment]
There is no stack trace either

**Comment by isapir** [comment]
Conversation moved to https://dev.lucee.org/t/websockets-wrong-session-scope-in-listener-component/2188/12
